function* genFunc() {
    try {
      yield 1;
      yield 2;
      yield 3;
    } catch (e) {
      console.error(e);
    }
  }
  
  const generator = genFunc();
  
  console.log(generator.next()); // {value: 1, done: false}
  console.log(generator.throw('Error!')); // {value: undefined, done: true}
  