try {
    setTimeout(() => { throw new Error('Error!'); }, 1000);
  } catch (e) {
    // 에러를 캐치하지 못한다
    console.error('캐치한 에러', e);
  }
  